spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ysfTest
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org:
      security: debug
      springframework:
        web: debug
      hibernate: debug