spring:
  data:
    rest:
      base-path: /api
  main:
    allow-bean-definition-overriding: true

project:
  name: YourSoccerField
  version: 0.4.0
  description: Idea assumes that, the user registering to our application and loging into it, can book a place, where
    he can play football.

security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2dhkCFy8zchY2W7GzVjG
          o+QBcoluOXRXmtwNffjLZp9KyTQ4Z0fY1n1pYn9ARAT/CJrMH75XIZxF53Kr6sI3
          1ZR1KHlLCcqg7R4Z3koCTblAVJPDKfSswG6eboW6bg+bc2/omwxhUpdzxGwtAtOG
          O5qXzwJg6sTMozbQn6T3xzWdKFwsrtDV6mLIt4jY5myM/DWXFEIGrh171R85LGCD
          ngjSzQrMMvzgAbmSVLWMOjfPVOoLMiOzUZJgc0zqdHO7VHaxYm/bVeyPAOqWzR72
          xUAP2zrpF/57XswuTmck4VyHcs4ixHvqa44VPTVY9sahLxtf8crv/Baj0igLuZri
          owIDAQAB
          -----END PUBLIC KEY-----