package com.pk.YourSoccerField.exception;

public enum ErrorCode {

    //INPUT VALIDATION
    INVALID_INPUT,

    //NOT FOUND
    NOT_FOUND_NEXT_USER_CODE,
    NOT_FOUND_BY_EMAIL,
    NOT_FOUND_BY_NAME,
    NOT_FOUND_BY_ID,


    //USER
    UPDATE_NEXT_USER_CODE,
    INCORRECT_PASSWORD,
    UNACTIVATED_USER,
    DUPLICAT_USER_EMAIL,


    //OTHER
    INSERT_ERROR,
}
