package com.pk.YourSoccerField.exception;

public enum ErrorCode {

    //INPUT VALIDATION
    INVALID_INPUT,
    SOCCER_FIELD_NOT_OPEN,
    SOCCER_FIELD_CLOSED,
    BOOKING_CONFLICT,

    //NOT FOUND
    NOT_FOUND_NEXT_USER_CODE,
    NOT_FOUND_BY_EMAIL,
    NOT_FOUND_BY_NAME,
    NOT_FOUND_BY_ID,
    NOT_FOUND_LAST_USER_CODE,

    //USER
    UPDATE_NEXT_USER_CODE,
    INCORRECT_PASSWORD,
    UNACTIVATED_USER,
    DUPLICATE_USER_EMAIL,
    DUPLICATE_USER_NICKNAME,

    //OTHER
    INSERT_ERROR,
    OPEN_HOUR_GET_VALUE,
}
